---
title: "Figures-Data"
output: html_document
date: "2022-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Hemophilia in Europe Table

```{r}
#Create data frame table
European_Countries <- c("United Kingdom", "Russia", "Germany", "Spain")
#Define hemophilia cases as a number
Hemophilia_Cases <- c(1569, 1274, 774, 280)
Hemophilia_Europe <- data.frame(European_Countries, Hemophilia_Cases)
#Define countries as a factor, setting their order
Hemophilia_Europe$European_Countries <- factor(Hemophilia_Europe$European_Countries, levels=Hemophilia_Europe$European_Countries)
print(Hemophilia_Europe)

```

```{r}
install.packages("ggplot2")
library(ggplot2)
```

##Figure 1: Bar graph of Hemophilia B cases across select European countries. The UK and Russia have the most reported cases (1,569 and 1,274 people). Spain has the least amount of cases at 280 people.

```{r}
#creates bar graph using the table we created
ggplot(data = Hemophilia_Europe, aes(x=European_Countries, y=Hemophilia_Cases)) + geom_bar(stat = "identity", color= "blue", fill="red") + labs(x="European Countries", y= "Hemophilia B", ylim= c(250,1600))
```

##Figure 3: Pedigree of Known Carriers and Affected Royal Family Members Caption and insert

##Figure 4: Heat Density\* Caption

```{r}
#Upload spreadsheet. 
Europe_HemophiliaB_Percentage <-read.csv("Europe_HemophiliaB_Percentage.csv")

#Delete NO VALUE rows, create vector to delete values. 
Europe_HemophiliaB_Percentage <-Europe_HemophiliaB_Percentage[-c(2,5,8,9,10,11,13,21,24,25,27,29,30,31,32,35,41,50),]

#Create Bar Graph of all the countries and the percentage of Hemophilia B in the populations 
ggplot(data = Europe_HemophiliaB_Percentage, aes(x=European.Countries, y=Percentage.with.Hemophilia.B)) + geom_bar(stat = "identity", color="blue", fill="black") + labs(x = "European Countries", y= "Percentage of Hemophilia B", title = "Percentage of European Countries that have Hemophilia B") +theme(axis.text.x = element_text(angle = 45, size = 9,color = "black", face = "plain", vjust = 1, hjust = 1),plot.margin = margin(10, 10, 10, 10))

```

##Figure 5: Heat Density Map
```{r}
#Upload spreadsheet
LikelihoodScores <-read.csv("LikelihoodScores.csv")

#Access ggplot 
library(ggplot2)
#Install reshape2
install.packages("reshape2")
library(reshape2)

#Create heat map of royal houses and average score of Hemophilia in each house
data <- cor(LikelihoodScores[sapply(LikelihoodScores,is.numeric)])
 
data1 <- melt(data)
 
ggplot(data1, aes(x = Var1,
                  y = Var2,
                  fill = value))+geom_tile()
```

